Domain\Model\Pokemon:
    type: entity
    table: pokemon
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        types:
            type: simple_array
        images:
            type: json
        baseExperience:
            type: smallint